
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'replicator' IDENTIFIED BY 'replpass';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'debezium' IDENTIFIED BY 'dbz';

CREATE DATABASE origin;
GRANT ALL PRIVILEGES ON origin.* TO 'mysqluser'@'%';

USE origin;

create table USER
(
    USER_ID    VARCHAR(5) not null,
    FIRST_NAME VARCHAR(64),
    LAST_NAME  VARCHAR(64),
    HEIGHT     DECIMAL(10, 6),

    constraint USER_PK primary key (USER_ID)
);

LOAD DATA LOCAL INFILE './csv/user.csv' INTO TABLE USER FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES
(USER_ID, FIRST_NAME, LAST_NAME, HEIGHT)
;

